manifest:
  remotes:
    - name: WhyNotBro235
      url-base: https://github.com/WhyNotBro235
  projects:
    - name: zmk
      remote: WhyNotBro235
      revision: main
      import: app/west.yml
  self:
    path: config
